config/routes.rb
Rails.application.routes.draw do
  get 'about/index'
  resources :listings
  resources :snacks
  resources :about
  # To create a first name in devise, we need to create a block and a registration_controller.rb
  devise_for :users, controllers: { registrations: 'registrations' }
  root 'snacks#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  require 'carrierwave'
  require 'carrierwave/orm/activerecord'
end

app/models/listing.rb
class Listing < ApplicationRecord
end

app/models/snack.rb
class Snack < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :user



    validates :title, :brand, presence: true
    validates :description, length: { maximum: 1000, too_long: "%{count} characters is the maximum allowed." }
    validates :title, length: { maximum: 140, too_long: "%{count} characters is the maximum allowed" }
    validates :price, numericality: { only_integer: true }, length: { maximum: 7 }

    BRAND = %w{ KitKat Pocky Yakuza }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :snacks

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :price, :difficulty, :description, :time, :volenteer)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController


private

def sign_up_params
  params.require(:user).permit(:name, :email, :password, :password_confirmation)
end

# If we want to update an account
def account_update_params
params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
end


end

app/controllers/snacks_controller.rb
class SnacksController < ApplicationController
  before_action :set_snack, only: [:show, :edit, :update, :destroy]

  # GET /snacks
  # GET /snacks.json
  def index
    @snacks = Snack.all.order("created_at desc")
  end

  # GET /snacks/1
  # GET /snacks/1.json
  def show
  end

  # GET /snacks/new
  def new
    @snack = current_user.snacks.build
  end

  # GET /snacks/1/edit
  def edit
  end

  # POST /snacks
  # POST /snacks.json
  def create
    @snack = current_user.snacks.build(snack_params)

    respond_to do |format|
      if @snack.save
        format.html { redirect_to @snack, notice: 'Snack was successfully created.' }
        format.json { render :show, status: :created, location: @snack }
      else
        format.html { render :new }
        format.json { render json: @snack.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /snacks/1
  # PATCH/PUT /snacks/1.json
  def update
    respond_to do |format|
      if @snack.update(snack_params)
        format.html { redirect_to @snack, notice: 'Snack was successfully updated.' }
        format.json { render :show, status: :ok, location: @snack }
      else
        format.html { render :edit }
        format.json { render json: @snack.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /snacks/1
  # DELETE /snacks/1.json
  def destroy
    @snack.destroy
    respond_to do |format|
      format.html { redirect_to snacks_url, notice: 'Snack was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_snack
      @snack = Snack.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def snack_params
      params.require(:snack).permit(:title, :brand, :description, :price, :image)
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/snacks_helper.rb
module SnacksHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/about/index.html.erb
<h1>About#index</h1>
<p>Find me in app/views/about/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GigHelp</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body class="<%= yield (:body_class) %>">
    <% if flash[:notice] %>
      <div class="notification is-success global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
    <div class="notification is-danger global-notification">
      <p class="alert"><%= alert %></p>
    </div>
    <% end %>
     <nav class="navbar is-warning is-primary is-bold" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
          <figure class="image is-96x96">
              <%= link_to image_tag("GigHelp.png") %>
          </figure>
      <div class="navbar-burger burger" data-target="navbar">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>

      <div id="navbar" class="navbar-menu">
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="field is-grouped">


            <% if user_signed_in? %>

            <div id="nav_example" class"navbar-menu">
              <div class="navbar-start">
                <a class="navbar-item" href="https://bulma.io/">
                Browse Jobs
                </a>
                <%= link_to "Create Job", listings_path, :class => "navbar-item" %>
                <a class="navbar-item" href="https://bulma.io/">
                How We Work
                </a>
            </div>
          </div>

              <div class="navbar-item has-dropdown is-hoverable">
                <%= link_to 'Account', edit_user_registration_path, class: "navbar-link" %>
                <div class="navbar-dropdown is-right">
                  <%= link_to "Profile Account", edit_user_registration_path, class:"navbar-item" %>
                  <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"navbar-item" %>
                </div>
              </div>

            <% else %>

            <%= link_to "Sign In", new_user_session_path, class:"navbar-item button is-warning" %>
            <%= link_to "Sign up", new_user_registration_path, class:"navbar-item button is-warning"%>

            <% end %>

            </div>
          </div>
        </div>
    </div>
  </nav>

  <%= yield(:header) %>

  <div class="container">

    <%= yield %>

  </div>

  </body>
</html>

app/views/listings/_form.html.erb
<%= simple_form_for(@listing) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :price %>
    <%= f.input :difficulty %>
    <%= f.input :description %>
    <%= f.input :time %>
    <%= f.input :volenteer %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Difficulty</th>
      <th>Description</th>
      <th>Time</th>
      <th>Volenteer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.name %></td>
        <td><%= listing.price %></td>
        <td><%= listing.difficulty %></td>
        <td><%= listing.description %></td>
        <td><%= listing.time %></td>
        <td><%= listing.volenteer %></td>
        <td><%= link_to 'Show', listing %></td>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listing', new_listing_path %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @listing.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @listing.price %>
</p>

<p>
  <strong>Difficulty:</strong>
  <%= @listing.difficulty %>
</p>

<p>
  <strong>Description:</strong>
  <%= @listing.description %>
</p>

<p>
  <strong>Time:</strong>
  <%= @listing.time %>
</p>

<p>
  <strong>Volenteer:</strong>
  <%= @listing.volenteer %>
</p>

<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>

app/views/snacks/_form.html.erb
<div class="columns">
  <div class="column is-8 is-centered">

    <%= simple_form_for @snack, html: { multipart: true } do |f| %>
      <%= f.error_notification %>

        <div class="columns">

          <div class="field column is-9">
            <div class="control">
              <%= f.input :title , required: true, input_html: { class: "input"}, wrapper: false, label_html: { class:"label" } %>
            </div>
          </div>

          <div class="field column">
            <div class="control">
              <%= f.input :price, required: true, input_html: { class:"input", maxlength: 7  }, wrapper: false, label_html: { class:"label" } %>
            </div>
          </div>

        </div>

        <div class="field">
          <div class="control">
            <%= f.input :description, required: true, input_html: { class:"textarea" }, wrapper: false, label_html: { class:"label" } %>
          </div>
        </div>

        <div class="columns">
          <div class="field column is-4">
            <div class="control">
              <label class="label">Brand</label>
              <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :brand, collection: Snack::BRAND, prompt: "Select brand" %>
                </span>
                <span class="icon is-small is-left">
                  <i class="fa fa-tag"></i>
                </span>
              </div>
            </div>
           </div>

        <div class="field">
          <div class="control">
            <label class="label">Add images</label>
              <div class="file">
              <label class="file-label">
                <%= f.input :image, as: :file, input_html: { class:"file-input instrument-image" }, label: false, wrapper: false %>
                  <span class="file-cta">
                    <span class="file-icon"><i class="fa fa-upload"></i></span>
                    <span class="file-label">Choose a file…</span>
                  </span>
              </label>
              </div>
            </div>
          </div>
          <output id="list"></output>
        <hr/>

        <div class="field is-grouped">
          <div class="control">
            <%= f.button :submit, class: 'button is-warning' %>
            <%= link_to 'Cancel', snacks_path, class:'button is-light' %>
          </div>
        </div>

      <% end %>
  </div>
</div>

app/views/snacks/_selling.html.erb
<div class="hero-body">
    <div class="container">
        <div class="columns is-vcentered">
            <div class="column is-6">
                <figure class="">
                  <%= link_to image_tag("landing.svg") %>
                </figure>
            </div>
            <div class="column is-5 is-offset-1 is-hero-title">
                <h1 class="title is-1 is-bigger">
                    Shared Marketplace
                </h1>
                <h2 class="subtitle is-4">
                    Work with people differently.
                </h2>
                <h3>The Gig economy is growing. We're here to support that. At GigHelp, we match the jobs your best at or what you need the most.</h3>
                <br>
                <p class="">
                    <a href="#" class="button button-cta is-bold btn-align secondary-btn raised">
                        Get Started
                    </a>
                </p>
            </div>
        </div>
    </div>
</div>

app/views/snacks/edit.html.erb
<h1>Editing Snack</h1>

<%= render 'form', snack: @snack %>

<%= link_to 'Show', @snack %> |
<%= link_to 'Back', snacks_path %>

app/views/snacks/index.html.erb
<% content_for :header do %>
<% end %>

<%= render 'snacks/selling' %>

<div class="section-title-wrapper has-text-centered">
    <!-- Divider -->
    <div class="special-divider">
        <span></span>
        <span></span>
    </div>
    <h2 class="title is-2">We are Different.</h2>
    <h4 class="subtitle is-4">All in one Collaboration.</h4>
</div>

<br><br><br><br><br><br><br><br><br><br><br><br>


<!-- <p id="notice"><%= notice %></p>

<h1>Snacks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Brand</th>
      <th>Description</th>
      <th>Price</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @snacks.each do |snack| %>
      <tr>
        <td><%= snack.title %></td>
        <td><%= snack.brand %></td>
        <td><%= snack.description %></td>
        <td><%= snack.price %></td>
        <td><%= snack.image %></td>
        <td><%= link_to 'Show', snack %></td>
        <td><%= link_to 'Edit', edit_snack_path(snack) %></td>
        <td><%= link_to 'Destroy', snack, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Snack', new_snack_path %> -->

app/views/snacks/new.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Sell a Snack
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="pv4">
  <%= render 'form', instrument: @snack%>
</div>

app/views/snacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @snack.title %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @snack.brand %>
</p>

<p>
  <strong>Description:</strong>
  <%= @snack.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @snack.price %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag (image_path(@snack.image.url(:thumb))), :class => "style_image" %>
</p>


<%= link_to 'Edit', edit_snack_path(@snack) %> |
<%= link_to 'Back', snacks_path %>

app/views/store/index.html.erb
<h1>Store#index</h1>
<p>Find me in app/views/store/index.html.erb</p>